getenv = TRUE
Universe = vanilla
Executable = randtest.py
arguments = bb1
Output = randresults/outs/bb1.out
Error = randresults/errs/bb1.err
Log = randresults/logs/bb1.log
queue

arguments = bb2
Output = randresults/outs/bb2.out
Error = randresults/errs/bb2.err
Log = randresults/logs/bb2.log
queue

arguments = bb3
Output = randresults/outs/bb3.out
Error = randresults/errs/bb3.err
Log = randresults/logs/bb3.log
queue

arguments = bb4
Output = randresults/outs/bb4.out
Error = randresults/errs/bb4.err
Log = randresults/logs/bb4.log
queue

arguments = bb5
Output = randresults/outs/bb5.out
Error = randresults/errs/bb5.err
Log = randresults/logs/bb5.log
queue

arguments = bb6
Output = randresults/outs/bb6.out
Error = randresults/errs/bb6.err
Log = randresults/logs/bb6.log
queue

arguments = bb7
Output = randresults/outs/bb7.out
Error = randresults/errs/bb7.err
Log = randresults/logs/bb7.log
queue

arguments = bb8
Output = randresults/outs/bb8.out
Error = randresults/errs/bb8.err
Log = randresults/logs/bb8.log
queue

arguments = bb9
Output = randresults/outs/bb9.out
Error = randresults/errs/bb9.err
Log = randresults/logs/bb9.log
queue

arguments = bb10
Output = randresults/outs/bb10.out
Error = randresults/errs/bb10.err
Log = randresults/logs/bb10.log
queue

arguments = bb11
Output = randresults/outs/bb11.out
Error = randresults/errs/bb11.err
Log = randresults/logs/bb11.log
queue

arguments = bb12
Output = randresults/outs/bb12.out
Error = randresults/errs/bb12.err
Log = randresults/logs/bb12.log
queue

arguments = bb13
Output = randresults/outs/bb13.out
Error = randresults/errs/bb13.err
Log = randresults/logs/bb13.log
queue

arguments = bb14
Output = randresults/outs/bb14.out
Error = randresults/errs/bb14.err
Log = randresults/logs/bb14.log
queue

arguments = bb15
Output = randresults/outs/bb15.out
Error = randresults/errs/bb15.err
Log = randresults/logs/bb15.log
queue

arguments = bb16
Output = randresults/outs/bb16.out
Error = randresults/errs/bb16.err
Log = randresults/logs/bb16.log
queue

arguments = bb17
Output = randresults/outs/bb17.out
Error = randresults/errs/bb17.err
Log = randresults/logs/bb17.log
queue

arguments = bb18
Output = randresults/outs/bb18.out
Error = randresults/errs/bb18.err
Log = randresults/logs/bb18.log
queue

arguments = bb19
Output = randresults/outs/bb19.out
Error = randresults/errs/bb19.err
Log = randresults/logs/bb19.log
queue

arguments = bb20
Output = randresults/outs/bb20.out
Error = randresults/errs/bb20.err
Log = randresults/logs/bb20.log
queue

arguments = bb21
Output = randresults/outs/bb21.out
Error = randresults/errs/bb21.err
Log = randresults/logs/bb21.log
queue

arguments = bb22
Output = randresults/outs/bb22.out
Error = randresults/errs/bb22.err
Log = randresults/logs/bb22.log
queue

arguments = bb23
Output = randresults/outs/bb23.out
Error = randresults/errs/bb23.err
Log = randresults/logs/bb23.log
queue

arguments = bb24
Output = randresults/outs/bb24.out
Error = randresults/errs/bb24.err
Log = randresults/logs/bb24.log
queue

arguments = bb25
Output = randresults/outs/bb25.out
Error = randresults/errs/bb25.err
Log = randresults/logs/bb25.log
queue

arguments = bb26
Output = randresults/outs/bb26.out
Error = randresults/errs/bb26.err
Log = randresults/logs/bb26.log
queue

arguments = bb27
Output = randresults/outs/bb27.out
Error = randresults/errs/bb27.err
Log = randresults/logs/bb27.log
queue

arguments = bb28
Output = randresults/outs/bb28.out
Error = randresults/errs/bb28.err
Log = randresults/logs/bb28.log
queue

arguments = bb29
Output = randresults/outs/bb29.out
Error = randresults/errs/bb29.err
Log = randresults/logs/bb29.log
queue

arguments = bb30
Output = randresults/outs/bb30.out
Error = randresults/errs/bb30.err
Log = randresults/logs/bb30.log
queue

arguments = bb31
Output = randresults/outs/bb31.out
Error = randresults/errs/bb31.err
Log = randresults/logs/bb31.log
queue

arguments = bb32
Output = randresults/outs/bb32.out
Error = randresults/errs/bb32.err
Log = randresults/logs/bb32.log
queue

arguments = bb33
Output = randresults/outs/bb33.out
Error = randresults/errs/bb33.err
Log = randresults/logs/bb33.log
queue

arguments = bb34
Output = randresults/outs/bb34.out
Error = randresults/errs/bb34.err
Log = randresults/logs/bb34.log
queue

arguments = bb35
Output = randresults/outs/bb35.out
Error = randresults/errs/bb35.err
Log = randresults/logs/bb35.log
queue

arguments = bb36
Output = randresults/outs/bb36.out
Error = randresults/errs/bb36.err
Log = randresults/logs/bb36.log
queue

arguments = bb37
Output = randresults/outs/bb37.out
Error = randresults/errs/bb37.err
Log = randresults/logs/bb37.log
queue

arguments = bb38
Output = randresults/outs/bb38.out
Error = randresults/errs/bb38.err
Log = randresults/logs/bb38.log
queue

arguments = bb39
Output = randresults/outs/bb39.out
Error = randresults/errs/bb39.err
Log = randresults/logs/bb39.log
queue

arguments = bb40
Output = randresults/outs/bb40.out
Error = randresults/errs/bb40.err
Log = randresults/logs/bb40.log
queue

arguments = bb41
Output = randresults/outs/bb41.out
Error = randresults/errs/bb41.err
Log = randresults/logs/bb41.log
queue

arguments = bb42
Output = randresults/outs/bb42.out
Error = randresults/errs/bb42.err
Log = randresults/logs/bb42.log
queue

arguments = bb43
Output = randresults/outs/bb43.out
Error = randresults/errs/bb43.err
Log = randresults/logs/bb43.log
queue

arguments = bb44
Output = randresults/outs/bb44.out
Error = randresults/errs/bb44.err
Log = randresults/logs/bb44.log
queue

arguments = bb45
Output = randresults/outs/bb45.out
Error = randresults/errs/bb45.err
Log = randresults/logs/bb45.log
queue

arguments = bb46
Output = randresults/outs/bb46.out
Error = randresults/errs/bb46.err
Log = randresults/logs/bb46.log
queue

arguments = bb47
Output = randresults/outs/bb47.out
Error = randresults/errs/bb47.err
Log = randresults/logs/bb47.log
queue

arguments = bb48
Output = randresults/outs/bb48.out
Error = randresults/errs/bb48.err
Log = randresults/logs/bb48.log
queue

arguments = bb49
Output = randresults/outs/bb49.out
Error = randresults/errs/bb49.err
Log = randresults/logs/bb49.log
queue

arguments = bb50
Output = randresults/outs/bb50.out
Error = randresults/errs/bb50.err
Log = randresults/logs/bb50.log
queue

arguments = bw1
Output = randresults/outs/bw1.out
Error = randresults/errs/bw1.err
Log = randresults/logs/bw1.log
queue

arguments = bw2
Output = randresults/outs/bw2.out
Error = randresults/errs/bw2.err
Log = randresults/logs/bw2.log
queue

arguments = bw3
Output = randresults/outs/bw3.out
Error = randresults/errs/bw3.err
Log = randresults/logs/bw3.log
queue

arguments = bw4
Output = randresults/outs/bw4.out
Error = randresults/errs/bw4.err
Log = randresults/logs/bw4.log
queue

arguments = bw5
Output = randresults/outs/bw5.out
Error = randresults/errs/bw5.err
Log = randresults/logs/bw5.log
queue

arguments = bw6
Output = randresults/outs/bw6.out
Error = randresults/errs/bw6.err
Log = randresults/logs/bw6.log
queue

arguments = bw7
Output = randresults/outs/bw7.out
Error = randresults/errs/bw7.err
Log = randresults/logs/bw7.log
queue

arguments = bw8
Output = randresults/outs/bw8.out
Error = randresults/errs/bw8.err
Log = randresults/logs/bw8.log
queue

arguments = bw9
Output = randresults/outs/bw9.out
Error = randresults/errs/bw9.err
Log = randresults/logs/bw9.log
queue

arguments = bw10
Output = randresults/outs/bw10.out
Error = randresults/errs/bw10.err
Log = randresults/logs/bw10.log
queue

arguments = bw11
Output = randresults/outs/bw11.out
Error = randresults/errs/bw11.err
Log = randresults/logs/bw11.log
queue

arguments = bw12
Output = randresults/outs/bw12.out
Error = randresults/errs/bw12.err
Log = randresults/logs/bw12.log
queue

arguments = bw13
Output = randresults/outs/bw13.out
Error = randresults/errs/bw13.err
Log = randresults/logs/bw13.log
queue

arguments = bw14
Output = randresults/outs/bw14.out
Error = randresults/errs/bw14.err
Log = randresults/logs/bw14.log
queue

arguments = bw15
Output = randresults/outs/bw15.out
Error = randresults/errs/bw15.err
Log = randresults/logs/bw15.log
queue

arguments = bw16
Output = randresults/outs/bw16.out
Error = randresults/errs/bw16.err
Log = randresults/logs/bw16.log
queue

arguments = bw17
Output = randresults/outs/bw17.out
Error = randresults/errs/bw17.err
Log = randresults/logs/bw17.log
queue

arguments = bw18
Output = randresults/outs/bw18.out
Error = randresults/errs/bw18.err
Log = randresults/logs/bw18.log
queue

arguments = bw19
Output = randresults/outs/bw19.out
Error = randresults/errs/bw19.err
Log = randresults/logs/bw19.log
queue

arguments = bw20
Output = randresults/outs/bw20.out
Error = randresults/errs/bw20.err
Log = randresults/logs/bw20.log
queue

arguments = bw21
Output = randresults/outs/bw21.out
Error = randresults/errs/bw21.err
Log = randresults/logs/bw21.log
queue

arguments = bw22
Output = randresults/outs/bw22.out
Error = randresults/errs/bw22.err
Log = randresults/logs/bw22.log
queue

arguments = bw23
Output = randresults/outs/bw23.out
Error = randresults/errs/bw23.err
Log = randresults/logs/bw23.log
queue

arguments = bw24
Output = randresults/outs/bw24.out
Error = randresults/errs/bw24.err
Log = randresults/logs/bw24.log
queue

arguments = bw25
Output = randresults/outs/bw25.out
Error = randresults/errs/bw25.err
Log = randresults/logs/bw25.log
queue

arguments = bw26
Output = randresults/outs/bw26.out
Error = randresults/errs/bw26.err
Log = randresults/logs/bw26.log
queue

arguments = bw27
Output = randresults/outs/bw27.out
Error = randresults/errs/bw27.err
Log = randresults/logs/bw27.log
queue

arguments = bw28
Output = randresults/outs/bw28.out
Error = randresults/errs/bw28.err
Log = randresults/logs/bw28.log
queue

arguments = bw29
Output = randresults/outs/bw29.out
Error = randresults/errs/bw29.err
Log = randresults/logs/bw29.log
queue

arguments = bw30
Output = randresults/outs/bw30.out
Error = randresults/errs/bw30.err
Log = randresults/logs/bw30.log
queue

arguments = bw31
Output = randresults/outs/bw31.out
Error = randresults/errs/bw31.err
Log = randresults/logs/bw31.log
queue

arguments = bw32
Output = randresults/outs/bw32.out
Error = randresults/errs/bw32.err
Log = randresults/logs/bw32.log
queue

arguments = bw33
Output = randresults/outs/bw33.out
Error = randresults/errs/bw33.err
Log = randresults/logs/bw33.log
queue

arguments = bw34
Output = randresults/outs/bw34.out
Error = randresults/errs/bw34.err
Log = randresults/logs/bw34.log
queue

arguments = bw35
Output = randresults/outs/bw35.out
Error = randresults/errs/bw35.err
Log = randresults/logs/bw35.log
queue

arguments = bw36
Output = randresults/outs/bw36.out
Error = randresults/errs/bw36.err
Log = randresults/logs/bw36.log
queue

arguments = bw37
Output = randresults/outs/bw37.out
Error = randresults/errs/bw37.err
Log = randresults/logs/bw37.log
queue

arguments = bw38
Output = randresults/outs/bw38.out
Error = randresults/errs/bw38.err
Log = randresults/logs/bw38.log
queue

arguments = bw39
Output = randresults/outs/bw39.out
Error = randresults/errs/bw39.err
Log = randresults/logs/bw39.log
queue

arguments = bw40
Output = randresults/outs/bw40.out
Error = randresults/errs/bw40.err
Log = randresults/logs/bw40.log
queue

arguments = bw41
Output = randresults/outs/bw41.out
Error = randresults/errs/bw41.err
Log = randresults/logs/bw41.log
queue

arguments = bw42
Output = randresults/outs/bw42.out
Error = randresults/errs/bw42.err
Log = randresults/logs/bw42.log
queue

arguments = bw43
Output = randresults/outs/bw43.out
Error = randresults/errs/bw43.err
Log = randresults/logs/bw43.log
queue

arguments = bw44
Output = randresults/outs/bw44.out
Error = randresults/errs/bw44.err
Log = randresults/logs/bw44.log
queue

arguments = bw45
Output = randresults/outs/bw45.out
Error = randresults/errs/bw45.err
Log = randresults/logs/bw45.log
queue

arguments = bw46
Output = randresults/outs/bw46.out
Error = randresults/errs/bw46.err
Log = randresults/logs/bw46.log
queue

arguments = bw47
Output = randresults/outs/bw47.out
Error = randresults/errs/bw47.err
Log = randresults/logs/bw47.log
queue

arguments = bw48
Output = randresults/outs/bw48.out
Error = randresults/errs/bw48.err
Log = randresults/logs/bw48.log
queue

arguments = bw49
Output = randresults/outs/bw49.out
Error = randresults/errs/bw49.err
Log = randresults/logs/bw49.log
queue

arguments = bw50
Output = randresults/outs/bw50.out
Error = randresults/errs/bw50.err
Log = randresults/logs/bw50.log
queue

arguments = bz1
Output = randresults/outs/bz1.out
Error = randresults/errs/bz1.err
Log = randresults/logs/bz1.log
queue

arguments = bz2
Output = randresults/outs/bz2.out
Error = randresults/errs/bz2.err
Log = randresults/logs/bz2.log
queue

arguments = bz3
Output = randresults/outs/bz3.out
Error = randresults/errs/bz3.err
Log = randresults/logs/bz3.log
queue

arguments = bz4
Output = randresults/outs/bz4.out
Error = randresults/errs/bz4.err
Log = randresults/logs/bz4.log
queue

arguments = bz5
Output = randresults/outs/bz5.out
Error = randresults/errs/bz5.err
Log = randresults/logs/bz5.log
queue

arguments = bz6
Output = randresults/outs/bz6.out
Error = randresults/errs/bz6.err
Log = randresults/logs/bz6.log
queue

arguments = bz7
Output = randresults/outs/bz7.out
Error = randresults/errs/bz7.err
Log = randresults/logs/bz7.log
queue

arguments = bz8
Output = randresults/outs/bz8.out
Error = randresults/errs/bz8.err
Log = randresults/logs/bz8.log
queue

arguments = bz9
Output = randresults/outs/bz9.out
Error = randresults/errs/bz9.err
Log = randresults/logs/bz9.log
queue

arguments = bz10
Output = randresults/outs/bz10.out
Error = randresults/errs/bz10.err
Log = randresults/logs/bz10.log
queue

arguments = bz11
Output = randresults/outs/bz11.out
Error = randresults/errs/bz11.err
Log = randresults/logs/bz11.log
queue

arguments = bz12
Output = randresults/outs/bz12.out
Error = randresults/errs/bz12.err
Log = randresults/logs/bz12.log
queue

arguments = bz13
Output = randresults/outs/bz13.out
Error = randresults/errs/bz13.err
Log = randresults/logs/bz13.log
queue

arguments = bz14
Output = randresults/outs/bz14.out
Error = randresults/errs/bz14.err
Log = randresults/logs/bz14.log
queue

arguments = bz15
Output = randresults/outs/bz15.out
Error = randresults/errs/bz15.err
Log = randresults/logs/bz15.log
queue

arguments = bz16
Output = randresults/outs/bz16.out
Error = randresults/errs/bz16.err
Log = randresults/logs/bz16.log
queue

arguments = bz17
Output = randresults/outs/bz17.out
Error = randresults/errs/bz17.err
Log = randresults/logs/bz17.log
queue

arguments = bz18
Output = randresults/outs/bz18.out
Error = randresults/errs/bz18.err
Log = randresults/logs/bz18.log
queue

arguments = bz19
Output = randresults/outs/bz19.out
Error = randresults/errs/bz19.err
Log = randresults/logs/bz19.log
queue

arguments = bz20
Output = randresults/outs/bz20.out
Error = randresults/errs/bz20.err
Log = randresults/logs/bz20.log
queue

arguments = bz21
Output = randresults/outs/bz21.out
Error = randresults/errs/bz21.err
Log = randresults/logs/bz21.log
queue

arguments = bz22
Output = randresults/outs/bz22.out
Error = randresults/errs/bz22.err
Log = randresults/logs/bz22.log
queue

arguments = bz23
Output = randresults/outs/bz23.out
Error = randresults/errs/bz23.err
Log = randresults/logs/bz23.log
queue

arguments = bz24
Output = randresults/outs/bz24.out
Error = randresults/errs/bz24.err
Log = randresults/logs/bz24.log
queue

arguments = bz25
Output = randresults/outs/bz25.out
Error = randresults/errs/bz25.err
Log = randresults/logs/bz25.log
queue

arguments = bz26
Output = randresults/outs/bz26.out
Error = randresults/errs/bz26.err
Log = randresults/logs/bz26.log
queue

arguments = bz27
Output = randresults/outs/bz27.out
Error = randresults/errs/bz27.err
Log = randresults/logs/bz27.log
queue

arguments = bz28
Output = randresults/outs/bz28.out
Error = randresults/errs/bz28.err
Log = randresults/logs/bz28.log
queue

arguments = bz29
Output = randresults/outs/bz29.out
Error = randresults/errs/bz29.err
Log = randresults/logs/bz29.log
queue

arguments = bz30
Output = randresults/outs/bz30.out
Error = randresults/errs/bz30.err
Log = randresults/logs/bz30.log
queue

arguments = bz31
Output = randresults/outs/bz31.out
Error = randresults/errs/bz31.err
Log = randresults/logs/bz31.log
queue

arguments = bz32
Output = randresults/outs/bz32.out
Error = randresults/errs/bz32.err
Log = randresults/logs/bz32.log
queue

arguments = bz33
Output = randresults/outs/bz33.out
Error = randresults/errs/bz33.err
Log = randresults/logs/bz33.log
queue

arguments = bz34
Output = randresults/outs/bz34.out
Error = randresults/errs/bz34.err
Log = randresults/logs/bz34.log
queue

arguments = bz35
Output = randresults/outs/bz35.out
Error = randresults/errs/bz35.err
Log = randresults/logs/bz35.log
queue

arguments = bz36
Output = randresults/outs/bz36.out
Error = randresults/errs/bz36.err
Log = randresults/logs/bz36.log
queue

arguments = bz37
Output = randresults/outs/bz37.out
Error = randresults/errs/bz37.err
Log = randresults/logs/bz37.log
queue

arguments = bz38
Output = randresults/outs/bz38.out
Error = randresults/errs/bz38.err
Log = randresults/logs/bz38.log
queue

arguments = bz39
Output = randresults/outs/bz39.out
Error = randresults/errs/bz39.err
Log = randresults/logs/bz39.log
queue

arguments = bz40
Output = randresults/outs/bz40.out
Error = randresults/errs/bz40.err
Log = randresults/logs/bz40.log
queue

arguments = bz41
Output = randresults/outs/bz41.out
Error = randresults/errs/bz41.err
Log = randresults/logs/bz41.log
queue

arguments = bz42
Output = randresults/outs/bz42.out
Error = randresults/errs/bz42.err
Log = randresults/logs/bz42.log
queue

arguments = bz43
Output = randresults/outs/bz43.out
Error = randresults/errs/bz43.err
Log = randresults/logs/bz43.log
queue

arguments = bz44
Output = randresults/outs/bz44.out
Error = randresults/errs/bz44.err
Log = randresults/logs/bz44.log
queue

arguments = bz45
Output = randresults/outs/bz45.out
Error = randresults/errs/bz45.err
Log = randresults/logs/bz45.log
queue

arguments = bz46
Output = randresults/outs/bz46.out
Error = randresults/errs/bz46.err
Log = randresults/logs/bz46.log
queue

arguments = bz47
Output = randresults/outs/bz47.out
Error = randresults/errs/bz47.err
Log = randresults/logs/bz47.log
queue

arguments = bz48
Output = randresults/outs/bz48.out
Error = randresults/errs/bz48.err
Log = randresults/logs/bz48.log
queue

arguments = bz49
Output = randresults/outs/bz49.out
Error = randresults/errs/bz49.err
Log = randresults/logs/bz49.log
queue

arguments = bz50
Output = randresults/outs/bz50.out
Error = randresults/errs/bz50.err
Log = randresults/logs/bz50.log
queue

arguments = qb1
Output = randresults/outs/qb1.out
Error = randresults/errs/qb1.err
Log = randresults/logs/qb1.log
queue

arguments = qb2
Output = randresults/outs/qb2.out
Error = randresults/errs/qb2.err
Log = randresults/logs/qb2.log
queue

arguments = qb3
Output = randresults/outs/qb3.out
Error = randresults/errs/qb3.err
Log = randresults/logs/qb3.log
queue

arguments = qb4
Output = randresults/outs/qb4.out
Error = randresults/errs/qb4.err
Log = randresults/logs/qb4.log
queue

arguments = qb5
Output = randresults/outs/qb5.out
Error = randresults/errs/qb5.err
Log = randresults/logs/qb5.log
queue

arguments = qb6
Output = randresults/outs/qb6.out
Error = randresults/errs/qb6.err
Log = randresults/logs/qb6.log
queue

arguments = qb7
Output = randresults/outs/qb7.out
Error = randresults/errs/qb7.err
Log = randresults/logs/qb7.log
queue

arguments = qb8
Output = randresults/outs/qb8.out
Error = randresults/errs/qb8.err
Log = randresults/logs/qb8.log
queue

arguments = qb9
Output = randresults/outs/qb9.out
Error = randresults/errs/qb9.err
Log = randresults/logs/qb9.log
queue

arguments = qb10
Output = randresults/outs/qb10.out
Error = randresults/errs/qb10.err
Log = randresults/logs/qb10.log
queue

arguments = qb11
Output = randresults/outs/qb11.out
Error = randresults/errs/qb11.err
Log = randresults/logs/qb11.log
queue

arguments = qb12
Output = randresults/outs/qb12.out
Error = randresults/errs/qb12.err
Log = randresults/logs/qb12.log
queue

arguments = qb13
Output = randresults/outs/qb13.out
Error = randresults/errs/qb13.err
Log = randresults/logs/qb13.log
queue

arguments = qb14
Output = randresults/outs/qb14.out
Error = randresults/errs/qb14.err
Log = randresults/logs/qb14.log
queue

arguments = qb15
Output = randresults/outs/qb15.out
Error = randresults/errs/qb15.err
Log = randresults/logs/qb15.log
queue

arguments = qb16
Output = randresults/outs/qb16.out
Error = randresults/errs/qb16.err
Log = randresults/logs/qb16.log
queue

arguments = qb17
Output = randresults/outs/qb17.out
Error = randresults/errs/qb17.err
Log = randresults/logs/qb17.log
queue

arguments = qb18
Output = randresults/outs/qb18.out
Error = randresults/errs/qb18.err
Log = randresults/logs/qb18.log
queue

arguments = qb19
Output = randresults/outs/qb19.out
Error = randresults/errs/qb19.err
Log = randresults/logs/qb19.log
queue

arguments = qb20
Output = randresults/outs/qb20.out
Error = randresults/errs/qb20.err
Log = randresults/logs/qb20.log
queue

arguments = qb21
Output = randresults/outs/qb21.out
Error = randresults/errs/qb21.err
Log = randresults/logs/qb21.log
queue

arguments = qb22
Output = randresults/outs/qb22.out
Error = randresults/errs/qb22.err
Log = randresults/logs/qb22.log
queue

arguments = qb23
Output = randresults/outs/qb23.out
Error = randresults/errs/qb23.err
Log = randresults/logs/qb23.log
queue

arguments = qb24
Output = randresults/outs/qb24.out
Error = randresults/errs/qb24.err
Log = randresults/logs/qb24.log
queue

arguments = qb25
Output = randresults/outs/qb25.out
Error = randresults/errs/qb25.err
Log = randresults/logs/qb25.log
queue

arguments = qb26
Output = randresults/outs/qb26.out
Error = randresults/errs/qb26.err
Log = randresults/logs/qb26.log
queue

arguments = qb27
Output = randresults/outs/qb27.out
Error = randresults/errs/qb27.err
Log = randresults/logs/qb27.log
queue

arguments = qb28
Output = randresults/outs/qb28.out
Error = randresults/errs/qb28.err
Log = randresults/logs/qb28.log
queue

arguments = qb29
Output = randresults/outs/qb29.out
Error = randresults/errs/qb29.err
Log = randresults/logs/qb29.log
queue

arguments = qb30
Output = randresults/outs/qb30.out
Error = randresults/errs/qb30.err
Log = randresults/logs/qb30.log
queue

arguments = qb31
Output = randresults/outs/qb31.out
Error = randresults/errs/qb31.err
Log = randresults/logs/qb31.log
queue

arguments = qb32
Output = randresults/outs/qb32.out
Error = randresults/errs/qb32.err
Log = randresults/logs/qb32.log
queue

arguments = qb33
Output = randresults/outs/qb33.out
Error = randresults/errs/qb33.err
Log = randresults/logs/qb33.log
queue

arguments = qb34
Output = randresults/outs/qb34.out
Error = randresults/errs/qb34.err
Log = randresults/logs/qb34.log
queue

arguments = qb35
Output = randresults/outs/qb35.out
Error = randresults/errs/qb35.err
Log = randresults/logs/qb35.log
queue

arguments = qb36
Output = randresults/outs/qb36.out
Error = randresults/errs/qb36.err
Log = randresults/logs/qb36.log
queue

arguments = qb37
Output = randresults/outs/qb37.out
Error = randresults/errs/qb37.err
Log = randresults/logs/qb37.log
queue

arguments = qb38
Output = randresults/outs/qb38.out
Error = randresults/errs/qb38.err
Log = randresults/logs/qb38.log
queue

arguments = qb39
Output = randresults/outs/qb39.out
Error = randresults/errs/qb39.err
Log = randresults/logs/qb39.log
queue

arguments = qb40
Output = randresults/outs/qb40.out
Error = randresults/errs/qb40.err
Log = randresults/logs/qb40.log
queue

arguments = qb41
Output = randresults/outs/qb41.out
Error = randresults/errs/qb41.err
Log = randresults/logs/qb41.log
queue

arguments = qb42
Output = randresults/outs/qb42.out
Error = randresults/errs/qb42.err
Log = randresults/logs/qb42.log
queue

arguments = qb43
Output = randresults/outs/qb43.out
Error = randresults/errs/qb43.err
Log = randresults/logs/qb43.log
queue

arguments = qb44
Output = randresults/outs/qb44.out
Error = randresults/errs/qb44.err
Log = randresults/logs/qb44.log
queue

arguments = qb45
Output = randresults/outs/qb45.out
Error = randresults/errs/qb45.err
Log = randresults/logs/qb45.log
queue

arguments = qb46
Output = randresults/outs/qb46.out
Error = randresults/errs/qb46.err
Log = randresults/logs/qb46.log
queue

arguments = qb47
Output = randresults/outs/qb47.out
Error = randresults/errs/qb47.err
Log = randresults/logs/qb47.log
queue

arguments = qb48
Output = randresults/outs/qb48.out
Error = randresults/errs/qb48.err
Log = randresults/logs/qb48.log
queue

arguments = qb49
Output = randresults/outs/qb49.out
Error = randresults/errs/qb49.err
Log = randresults/logs/qb49.log
queue

arguments = qb50
Output = randresults/outs/qb50.out
Error = randresults/errs/qb50.err
Log = randresults/logs/qb50.log
queue

arguments = qw1
Output = randresults/outs/qw1.out
Error = randresults/errs/qw1.err
Log = randresults/logs/qw1.log
queue

arguments = qw2
Output = randresults/outs/qw2.out
Error = randresults/errs/qw2.err
Log = randresults/logs/qw2.log
queue

arguments = qw3
Output = randresults/outs/qw3.out
Error = randresults/errs/qw3.err
Log = randresults/logs/qw3.log
queue

arguments = qw4
Output = randresults/outs/qw4.out
Error = randresults/errs/qw4.err
Log = randresults/logs/qw4.log
queue

arguments = qw5
Output = randresults/outs/qw5.out
Error = randresults/errs/qw5.err
Log = randresults/logs/qw5.log
queue

arguments = qw6
Output = randresults/outs/qw6.out
Error = randresults/errs/qw6.err
Log = randresults/logs/qw6.log
queue

arguments = qw7
Output = randresults/outs/qw7.out
Error = randresults/errs/qw7.err
Log = randresults/logs/qw7.log
queue

arguments = qw8
Output = randresults/outs/qw8.out
Error = randresults/errs/qw8.err
Log = randresults/logs/qw8.log
queue

arguments = qw9
Output = randresults/outs/qw9.out
Error = randresults/errs/qw9.err
Log = randresults/logs/qw9.log
queue

arguments = qw10
Output = randresults/outs/qw10.out
Error = randresults/errs/qw10.err
Log = randresults/logs/qw10.log
queue

arguments = qw11
Output = randresults/outs/qw11.out
Error = randresults/errs/qw11.err
Log = randresults/logs/qw11.log
queue

arguments = qw12
Output = randresults/outs/qw12.out
Error = randresults/errs/qw12.err
Log = randresults/logs/qw12.log
queue

arguments = qw13
Output = randresults/outs/qw13.out
Error = randresults/errs/qw13.err
Log = randresults/logs/qw13.log
queue

arguments = qw14
Output = randresults/outs/qw14.out
Error = randresults/errs/qw14.err
Log = randresults/logs/qw14.log
queue

arguments = qw15
Output = randresults/outs/qw15.out
Error = randresults/errs/qw15.err
Log = randresults/logs/qw15.log
queue

arguments = qw16
Output = randresults/outs/qw16.out
Error = randresults/errs/qw16.err
Log = randresults/logs/qw16.log
queue

arguments = qw17
Output = randresults/outs/qw17.out
Error = randresults/errs/qw17.err
Log = randresults/logs/qw17.log
queue

arguments = qw18
Output = randresults/outs/qw18.out
Error = randresults/errs/qw18.err
Log = randresults/logs/qw18.log
queue

arguments = qw19
Output = randresults/outs/qw19.out
Error = randresults/errs/qw19.err
Log = randresults/logs/qw19.log
queue

arguments = qw20
Output = randresults/outs/qw20.out
Error = randresults/errs/qw20.err
Log = randresults/logs/qw20.log
queue

arguments = qw21
Output = randresults/outs/qw21.out
Error = randresults/errs/qw21.err
Log = randresults/logs/qw21.log
queue

arguments = qw22
Output = randresults/outs/qw22.out
Error = randresults/errs/qw22.err
Log = randresults/logs/qw22.log
queue

arguments = qw23
Output = randresults/outs/qw23.out
Error = randresults/errs/qw23.err
Log = randresults/logs/qw23.log
queue

arguments = qw24
Output = randresults/outs/qw24.out
Error = randresults/errs/qw24.err
Log = randresults/logs/qw24.log
queue

arguments = qw25
Output = randresults/outs/qw25.out
Error = randresults/errs/qw25.err
Log = randresults/logs/qw25.log
queue

arguments = qw26
Output = randresults/outs/qw26.out
Error = randresults/errs/qw26.err
Log = randresults/logs/qw26.log
queue

arguments = qw27
Output = randresults/outs/qw27.out
Error = randresults/errs/qw27.err
Log = randresults/logs/qw27.log
queue

arguments = qw28
Output = randresults/outs/qw28.out
Error = randresults/errs/qw28.err
Log = randresults/logs/qw28.log
queue

arguments = qw29
Output = randresults/outs/qw29.out
Error = randresults/errs/qw29.err
Log = randresults/logs/qw29.log
queue

arguments = qw30
Output = randresults/outs/qw30.out
Error = randresults/errs/qw30.err
Log = randresults/logs/qw30.log
queue

arguments = qw31
Output = randresults/outs/qw31.out
Error = randresults/errs/qw31.err
Log = randresults/logs/qw31.log
queue

arguments = qw32
Output = randresults/outs/qw32.out
Error = randresults/errs/qw32.err
Log = randresults/logs/qw32.log
queue

arguments = qw33
Output = randresults/outs/qw33.out
Error = randresults/errs/qw33.err
Log = randresults/logs/qw33.log
queue

arguments = qw34
Output = randresults/outs/qw34.out
Error = randresults/errs/qw34.err
Log = randresults/logs/qw34.log
queue

arguments = qw35
Output = randresults/outs/qw35.out
Error = randresults/errs/qw35.err
Log = randresults/logs/qw35.log
queue

arguments = qw36
Output = randresults/outs/qw36.out
Error = randresults/errs/qw36.err
Log = randresults/logs/qw36.log
queue

arguments = qw37
Output = randresults/outs/qw37.out
Error = randresults/errs/qw37.err
Log = randresults/logs/qw37.log
queue

arguments = qw38
Output = randresults/outs/qw38.out
Error = randresults/errs/qw38.err
Log = randresults/logs/qw38.log
queue

arguments = qw39
Output = randresults/outs/qw39.out
Error = randresults/errs/qw39.err
Log = randresults/logs/qw39.log
queue

arguments = qw40
Output = randresults/outs/qw40.out
Error = randresults/errs/qw40.err
Log = randresults/logs/qw40.log
queue

arguments = qw41
Output = randresults/outs/qw41.out
Error = randresults/errs/qw41.err
Log = randresults/logs/qw41.log
queue

arguments = qw42
Output = randresults/outs/qw42.out
Error = randresults/errs/qw42.err
Log = randresults/logs/qw42.log
queue

arguments = qw43
Output = randresults/outs/qw43.out
Error = randresults/errs/qw43.err
Log = randresults/logs/qw43.log
queue

arguments = qw44
Output = randresults/outs/qw44.out
Error = randresults/errs/qw44.err
Log = randresults/logs/qw44.log
queue

arguments = qw45
Output = randresults/outs/qw45.out
Error = randresults/errs/qw45.err
Log = randresults/logs/qw45.log
queue

arguments = qw46
Output = randresults/outs/qw46.out
Error = randresults/errs/qw46.err
Log = randresults/logs/qw46.log
queue

arguments = qw47
Output = randresults/outs/qw47.out
Error = randresults/errs/qw47.err
Log = randresults/logs/qw47.log
queue

arguments = qw48
Output = randresults/outs/qw48.out
Error = randresults/errs/qw48.err
Log = randresults/logs/qw48.log
queue

arguments = qw49
Output = randresults/outs/qw49.out
Error = randresults/errs/qw49.err
Log = randresults/logs/qw49.log
queue

arguments = qw50
Output = randresults/outs/qw50.out
Error = randresults/errs/qw50.err
Log = randresults/logs/qw50.log
queue

arguments = qz1
Output = randresults/outs/qz1.out
Error = randresults/errs/qz1.err
Log = randresults/logs/qz1.log
queue

arguments = qz2
Output = randresults/outs/qz2.out
Error = randresults/errs/qz2.err
Log = randresults/logs/qz2.log
queue

arguments = qz3
Output = randresults/outs/qz3.out
Error = randresults/errs/qz3.err
Log = randresults/logs/qz3.log
queue

arguments = qz4
Output = randresults/outs/qz4.out
Error = randresults/errs/qz4.err
Log = randresults/logs/qz4.log
queue

arguments = qz5
Output = randresults/outs/qz5.out
Error = randresults/errs/qz5.err
Log = randresults/logs/qz5.log
queue

arguments = qz6
Output = randresults/outs/qz6.out
Error = randresults/errs/qz6.err
Log = randresults/logs/qz6.log
queue

arguments = qz7
Output = randresults/outs/qz7.out
Error = randresults/errs/qz7.err
Log = randresults/logs/qz7.log
queue

arguments = qz8
Output = randresults/outs/qz8.out
Error = randresults/errs/qz8.err
Log = randresults/logs/qz8.log
queue

arguments = qz9
Output = randresults/outs/qz9.out
Error = randresults/errs/qz9.err
Log = randresults/logs/qz9.log
queue

arguments = qz10
Output = randresults/outs/qz10.out
Error = randresults/errs/qz10.err
Log = randresults/logs/qz10.log
queue

arguments = qz11
Output = randresults/outs/qz11.out
Error = randresults/errs/qz11.err
Log = randresults/logs/qz11.log
queue

arguments = qz12
Output = randresults/outs/qz12.out
Error = randresults/errs/qz12.err
Log = randresults/logs/qz12.log
queue

arguments = qz13
Output = randresults/outs/qz13.out
Error = randresults/errs/qz13.err
Log = randresults/logs/qz13.log
queue

arguments = qz14
Output = randresults/outs/qz14.out
Error = randresults/errs/qz14.err
Log = randresults/logs/qz14.log
queue

arguments = qz15
Output = randresults/outs/qz15.out
Error = randresults/errs/qz15.err
Log = randresults/logs/qz15.log
queue

arguments = qz16
Output = randresults/outs/qz16.out
Error = randresults/errs/qz16.err
Log = randresults/logs/qz16.log
queue

arguments = qz17
Output = randresults/outs/qz17.out
Error = randresults/errs/qz17.err
Log = randresults/logs/qz17.log
queue

arguments = qz18
Output = randresults/outs/qz18.out
Error = randresults/errs/qz18.err
Log = randresults/logs/qz18.log
queue

arguments = qz19
Output = randresults/outs/qz19.out
Error = randresults/errs/qz19.err
Log = randresults/logs/qz19.log
queue

arguments = qz20
Output = randresults/outs/qz20.out
Error = randresults/errs/qz20.err
Log = randresults/logs/qz20.log
queue

arguments = qz21
Output = randresults/outs/qz21.out
Error = randresults/errs/qz21.err
Log = randresults/logs/qz21.log
queue

arguments = qz22
Output = randresults/outs/qz22.out
Error = randresults/errs/qz22.err
Log = randresults/logs/qz22.log
queue

arguments = qz23
Output = randresults/outs/qz23.out
Error = randresults/errs/qz23.err
Log = randresults/logs/qz23.log
queue

arguments = qz24
Output = randresults/outs/qz24.out
Error = randresults/errs/qz24.err
Log = randresults/logs/qz24.log
queue

arguments = qz25
Output = randresults/outs/qz25.out
Error = randresults/errs/qz25.err
Log = randresults/logs/qz25.log
queue

arguments = qz26
Output = randresults/outs/qz26.out
Error = randresults/errs/qz26.err
Log = randresults/logs/qz26.log
queue

arguments = qz27
Output = randresults/outs/qz27.out
Error = randresults/errs/qz27.err
Log = randresults/logs/qz27.log
queue

arguments = qz28
Output = randresults/outs/qz28.out
Error = randresults/errs/qz28.err
Log = randresults/logs/qz28.log
queue

arguments = qz29
Output = randresults/outs/qz29.out
Error = randresults/errs/qz29.err
Log = randresults/logs/qz29.log
queue

arguments = qz30
Output = randresults/outs/qz30.out
Error = randresults/errs/qz30.err
Log = randresults/logs/qz30.log
queue

arguments = qz31
Output = randresults/outs/qz31.out
Error = randresults/errs/qz31.err
Log = randresults/logs/qz31.log
queue

arguments = qz32
Output = randresults/outs/qz32.out
Error = randresults/errs/qz32.err
Log = randresults/logs/qz32.log
queue

arguments = qz33
Output = randresults/outs/qz33.out
Error = randresults/errs/qz33.err
Log = randresults/logs/qz33.log
queue

arguments = qz34
Output = randresults/outs/qz34.out
Error = randresults/errs/qz34.err
Log = randresults/logs/qz34.log
queue

arguments = qz35
Output = randresults/outs/qz35.out
Error = randresults/errs/qz35.err
Log = randresults/logs/qz35.log
queue

arguments = qz36
Output = randresults/outs/qz36.out
Error = randresults/errs/qz36.err
Log = randresults/logs/qz36.log
queue

arguments = qz37
Output = randresults/outs/qz37.out
Error = randresults/errs/qz37.err
Log = randresults/logs/qz37.log
queue

arguments = qz38
Output = randresults/outs/qz38.out
Error = randresults/errs/qz38.err
Log = randresults/logs/qz38.log
queue

arguments = qz39
Output = randresults/outs/qz39.out
Error = randresults/errs/qz39.err
Log = randresults/logs/qz39.log
queue

arguments = qz40
Output = randresults/outs/qz40.out
Error = randresults/errs/qz40.err
Log = randresults/logs/qz40.log
queue

arguments = qz41
Output = randresults/outs/qz41.out
Error = randresults/errs/qz41.err
Log = randresults/logs/qz41.log
queue

arguments = qz42
Output = randresults/outs/qz42.out
Error = randresults/errs/qz42.err
Log = randresults/logs/qz42.log
queue

arguments = qz43
Output = randresults/outs/qz43.out
Error = randresults/errs/qz43.err
Log = randresults/logs/qz43.log
queue

arguments = qz44
Output = randresults/outs/qz44.out
Error = randresults/errs/qz44.err
Log = randresults/logs/qz44.log
queue

arguments = qz45
Output = randresults/outs/qz45.out
Error = randresults/errs/qz45.err
Log = randresults/logs/qz45.log
queue

arguments = qz46
Output = randresults/outs/qz46.out
Error = randresults/errs/qz46.err
Log = randresults/logs/qz46.log
queue

arguments = qz47
Output = randresults/outs/qz47.out
Error = randresults/errs/qz47.err
Log = randresults/logs/qz47.log
queue

arguments = qz48
Output = randresults/outs/qz48.out
Error = randresults/errs/qz48.err
Log = randresults/logs/qz48.log
queue

arguments = qz49
Output = randresults/outs/qz49.out
Error = randresults/errs/qz49.err
Log = randresults/logs/qz49.log
queue

arguments = qz50
Output = randresults/outs/qz50.out
Error = randresults/errs/qz50.err
Log = randresults/logs/qz50.log
queue

arguments = wb1
Output = randresults/outs/wb1.out
Error = randresults/errs/wb1.err
Log = randresults/logs/wb1.log
queue

arguments = wb2
Output = randresults/outs/wb2.out
Error = randresults/errs/wb2.err
Log = randresults/logs/wb2.log
queue

arguments = wb3
Output = randresults/outs/wb3.out
Error = randresults/errs/wb3.err
Log = randresults/logs/wb3.log
queue

arguments = wb4
Output = randresults/outs/wb4.out
Error = randresults/errs/wb4.err
Log = randresults/logs/wb4.log
queue

arguments = wb5
Output = randresults/outs/wb5.out
Error = randresults/errs/wb5.err
Log = randresults/logs/wb5.log
queue

arguments = wb6
Output = randresults/outs/wb6.out
Error = randresults/errs/wb6.err
Log = randresults/logs/wb6.log
queue

arguments = wb7
Output = randresults/outs/wb7.out
Error = randresults/errs/wb7.err
Log = randresults/logs/wb7.log
queue

arguments = wb8
Output = randresults/outs/wb8.out
Error = randresults/errs/wb8.err
Log = randresults/logs/wb8.log
queue

arguments = wb9
Output = randresults/outs/wb9.out
Error = randresults/errs/wb9.err
Log = randresults/logs/wb9.log
queue

arguments = wb10
Output = randresults/outs/wb10.out
Error = randresults/errs/wb10.err
Log = randresults/logs/wb10.log
queue

arguments = wb11
Output = randresults/outs/wb11.out
Error = randresults/errs/wb11.err
Log = randresults/logs/wb11.log
queue

arguments = wb12
Output = randresults/outs/wb12.out
Error = randresults/errs/wb12.err
Log = randresults/logs/wb12.log
queue

arguments = wb13
Output = randresults/outs/wb13.out
Error = randresults/errs/wb13.err
Log = randresults/logs/wb13.log
queue

arguments = wb14
Output = randresults/outs/wb14.out
Error = randresults/errs/wb14.err
Log = randresults/logs/wb14.log
queue

arguments = wb15
Output = randresults/outs/wb15.out
Error = randresults/errs/wb15.err
Log = randresults/logs/wb15.log
queue

arguments = wb16
Output = randresults/outs/wb16.out
Error = randresults/errs/wb16.err
Log = randresults/logs/wb16.log
queue

arguments = wb17
Output = randresults/outs/wb17.out
Error = randresults/errs/wb17.err
Log = randresults/logs/wb17.log
queue

arguments = wb18
Output = randresults/outs/wb18.out
Error = randresults/errs/wb18.err
Log = randresults/logs/wb18.log
queue

arguments = wb19
Output = randresults/outs/wb19.out
Error = randresults/errs/wb19.err
Log = randresults/logs/wb19.log
queue

arguments = wb20
Output = randresults/outs/wb20.out
Error = randresults/errs/wb20.err
Log = randresults/logs/wb20.log
queue

arguments = wb21
Output = randresults/outs/wb21.out
Error = randresults/errs/wb21.err
Log = randresults/logs/wb21.log
queue

arguments = wb22
Output = randresults/outs/wb22.out
Error = randresults/errs/wb22.err
Log = randresults/logs/wb22.log
queue

arguments = wb23
Output = randresults/outs/wb23.out
Error = randresults/errs/wb23.err
Log = randresults/logs/wb23.log
queue

arguments = wb24
Output = randresults/outs/wb24.out
Error = randresults/errs/wb24.err
Log = randresults/logs/wb24.log
queue

arguments = wb25
Output = randresults/outs/wb25.out
Error = randresults/errs/wb25.err
Log = randresults/logs/wb25.log
queue

arguments = wb26
Output = randresults/outs/wb26.out
Error = randresults/errs/wb26.err
Log = randresults/logs/wb26.log
queue

arguments = wb27
Output = randresults/outs/wb27.out
Error = randresults/errs/wb27.err
Log = randresults/logs/wb27.log
queue

arguments = wb28
Output = randresults/outs/wb28.out
Error = randresults/errs/wb28.err
Log = randresults/logs/wb28.log
queue

arguments = wb29
Output = randresults/outs/wb29.out
Error = randresults/errs/wb29.err
Log = randresults/logs/wb29.log
queue

arguments = wb30
Output = randresults/outs/wb30.out
Error = randresults/errs/wb30.err
Log = randresults/logs/wb30.log
queue

arguments = wb31
Output = randresults/outs/wb31.out
Error = randresults/errs/wb31.err
Log = randresults/logs/wb31.log
queue

arguments = wb32
Output = randresults/outs/wb32.out
Error = randresults/errs/wb32.err
Log = randresults/logs/wb32.log
queue

arguments = wb33
Output = randresults/outs/wb33.out
Error = randresults/errs/wb33.err
Log = randresults/logs/wb33.log
queue

arguments = wb34
Output = randresults/outs/wb34.out
Error = randresults/errs/wb34.err
Log = randresults/logs/wb34.log
queue

arguments = wb35
Output = randresults/outs/wb35.out
Error = randresults/errs/wb35.err
Log = randresults/logs/wb35.log
queue

arguments = wb36
Output = randresults/outs/wb36.out
Error = randresults/errs/wb36.err
Log = randresults/logs/wb36.log
queue

arguments = wb37
Output = randresults/outs/wb37.out
Error = randresults/errs/wb37.err
Log = randresults/logs/wb37.log
queue

arguments = wb38
Output = randresults/outs/wb38.out
Error = randresults/errs/wb38.err
Log = randresults/logs/wb38.log
queue

arguments = wb39
Output = randresults/outs/wb39.out
Error = randresults/errs/wb39.err
Log = randresults/logs/wb39.log
queue

arguments = wb40
Output = randresults/outs/wb40.out
Error = randresults/errs/wb40.err
Log = randresults/logs/wb40.log
queue

arguments = wb41
Output = randresults/outs/wb41.out
Error = randresults/errs/wb41.err
Log = randresults/logs/wb41.log
queue

arguments = wb42
Output = randresults/outs/wb42.out
Error = randresults/errs/wb42.err
Log = randresults/logs/wb42.log
queue

arguments = wb43
Output = randresults/outs/wb43.out
Error = randresults/errs/wb43.err
Log = randresults/logs/wb43.log
queue

arguments = wb44
Output = randresults/outs/wb44.out
Error = randresults/errs/wb44.err
Log = randresults/logs/wb44.log
queue

arguments = wb45
Output = randresults/outs/wb45.out
Error = randresults/errs/wb45.err
Log = randresults/logs/wb45.log
queue

arguments = wb46
Output = randresults/outs/wb46.out
Error = randresults/errs/wb46.err
Log = randresults/logs/wb46.log
queue

arguments = wb47
Output = randresults/outs/wb47.out
Error = randresults/errs/wb47.err
Log = randresults/logs/wb47.log
queue

arguments = wb48
Output = randresults/outs/wb48.out
Error = randresults/errs/wb48.err
Log = randresults/logs/wb48.log
queue

arguments = wb49
Output = randresults/outs/wb49.out
Error = randresults/errs/wb49.err
Log = randresults/logs/wb49.log
queue

arguments = wb50
Output = randresults/outs/wb50.out
Error = randresults/errs/wb50.err
Log = randresults/logs/wb50.log
queue

arguments = ww1
Output = randresults/outs/ww1.out
Error = randresults/errs/ww1.err
Log = randresults/logs/ww1.log
queue

arguments = ww2
Output = randresults/outs/ww2.out
Error = randresults/errs/ww2.err
Log = randresults/logs/ww2.log
queue

arguments = ww3
Output = randresults/outs/ww3.out
Error = randresults/errs/ww3.err
Log = randresults/logs/ww3.log
queue

arguments = ww4
Output = randresults/outs/ww4.out
Error = randresults/errs/ww4.err
Log = randresults/logs/ww4.log
queue

arguments = ww5
Output = randresults/outs/ww5.out
Error = randresults/errs/ww5.err
Log = randresults/logs/ww5.log
queue

arguments = ww6
Output = randresults/outs/ww6.out
Error = randresults/errs/ww6.err
Log = randresults/logs/ww6.log
queue

arguments = ww7
Output = randresults/outs/ww7.out
Error = randresults/errs/ww7.err
Log = randresults/logs/ww7.log
queue

arguments = ww8
Output = randresults/outs/ww8.out
Error = randresults/errs/ww8.err
Log = randresults/logs/ww8.log
queue

arguments = ww9
Output = randresults/outs/ww9.out
Error = randresults/errs/ww9.err
Log = randresults/logs/ww9.log
queue

arguments = ww10
Output = randresults/outs/ww10.out
Error = randresults/errs/ww10.err
Log = randresults/logs/ww10.log
queue

arguments = ww11
Output = randresults/outs/ww11.out
Error = randresults/errs/ww11.err
Log = randresults/logs/ww11.log
queue

arguments = ww12
Output = randresults/outs/ww12.out
Error = randresults/errs/ww12.err
Log = randresults/logs/ww12.log
queue

arguments = ww13
Output = randresults/outs/ww13.out
Error = randresults/errs/ww13.err
Log = randresults/logs/ww13.log
queue

arguments = ww14
Output = randresults/outs/ww14.out
Error = randresults/errs/ww14.err
Log = randresults/logs/ww14.log
queue

arguments = ww15
Output = randresults/outs/ww15.out
Error = randresults/errs/ww15.err
Log = randresults/logs/ww15.log
queue

arguments = ww16
Output = randresults/outs/ww16.out
Error = randresults/errs/ww16.err
Log = randresults/logs/ww16.log
queue

arguments = ww17
Output = randresults/outs/ww17.out
Error = randresults/errs/ww17.err
Log = randresults/logs/ww17.log
queue

arguments = ww18
Output = randresults/outs/ww18.out
Error = randresults/errs/ww18.err
Log = randresults/logs/ww18.log
queue

arguments = ww19
Output = randresults/outs/ww19.out
Error = randresults/errs/ww19.err
Log = randresults/logs/ww19.log
queue

arguments = ww20
Output = randresults/outs/ww20.out
Error = randresults/errs/ww20.err
Log = randresults/logs/ww20.log
queue

arguments = ww21
Output = randresults/outs/ww21.out
Error = randresults/errs/ww21.err
Log = randresults/logs/ww21.log
queue

arguments = ww22
Output = randresults/outs/ww22.out
Error = randresults/errs/ww22.err
Log = randresults/logs/ww22.log
queue

arguments = ww23
Output = randresults/outs/ww23.out
Error = randresults/errs/ww23.err
Log = randresults/logs/ww23.log
queue

arguments = ww24
Output = randresults/outs/ww24.out
Error = randresults/errs/ww24.err
Log = randresults/logs/ww24.log
queue

arguments = ww25
Output = randresults/outs/ww25.out
Error = randresults/errs/ww25.err
Log = randresults/logs/ww25.log
queue

arguments = ww26
Output = randresults/outs/ww26.out
Error = randresults/errs/ww26.err
Log = randresults/logs/ww26.log
queue

arguments = ww27
Output = randresults/outs/ww27.out
Error = randresults/errs/ww27.err
Log = randresults/logs/ww27.log
queue

arguments = ww28
Output = randresults/outs/ww28.out
Error = randresults/errs/ww28.err
Log = randresults/logs/ww28.log
queue

arguments = ww29
Output = randresults/outs/ww29.out
Error = randresults/errs/ww29.err
Log = randresults/logs/ww29.log
queue

arguments = ww30
Output = randresults/outs/ww30.out
Error = randresults/errs/ww30.err
Log = randresults/logs/ww30.log
queue

arguments = ww31
Output = randresults/outs/ww31.out
Error = randresults/errs/ww31.err
Log = randresults/logs/ww31.log
queue

arguments = ww32
Output = randresults/outs/ww32.out
Error = randresults/errs/ww32.err
Log = randresults/logs/ww32.log
queue

arguments = ww33
Output = randresults/outs/ww33.out
Error = randresults/errs/ww33.err
Log = randresults/logs/ww33.log
queue

arguments = ww34
Output = randresults/outs/ww34.out
Error = randresults/errs/ww34.err
Log = randresults/logs/ww34.log
queue

arguments = ww35
Output = randresults/outs/ww35.out
Error = randresults/errs/ww35.err
Log = randresults/logs/ww35.log
queue

arguments = ww36
Output = randresults/outs/ww36.out
Error = randresults/errs/ww36.err
Log = randresults/logs/ww36.log
queue

arguments = ww37
Output = randresults/outs/ww37.out
Error = randresults/errs/ww37.err
Log = randresults/logs/ww37.log
queue

arguments = ww38
Output = randresults/outs/ww38.out
Error = randresults/errs/ww38.err
Log = randresults/logs/ww38.log
queue

arguments = ww39
Output = randresults/outs/ww39.out
Error = randresults/errs/ww39.err
Log = randresults/logs/ww39.log
queue

arguments = ww40
Output = randresults/outs/ww40.out
Error = randresults/errs/ww40.err
Log = randresults/logs/ww40.log
queue

arguments = ww41
Output = randresults/outs/ww41.out
Error = randresults/errs/ww41.err
Log = randresults/logs/ww41.log
queue

arguments = ww42
Output = randresults/outs/ww42.out
Error = randresults/errs/ww42.err
Log = randresults/logs/ww42.log
queue

arguments = ww43
Output = randresults/outs/ww43.out
Error = randresults/errs/ww43.err
Log = randresults/logs/ww43.log
queue

arguments = ww44
Output = randresults/outs/ww44.out
Error = randresults/errs/ww44.err
Log = randresults/logs/ww44.log
queue

arguments = ww45
Output = randresults/outs/ww45.out
Error = randresults/errs/ww45.err
Log = randresults/logs/ww45.log
queue

arguments = ww46
Output = randresults/outs/ww46.out
Error = randresults/errs/ww46.err
Log = randresults/logs/ww46.log
queue

arguments = ww47
Output = randresults/outs/ww47.out
Error = randresults/errs/ww47.err
Log = randresults/logs/ww47.log
queue

arguments = ww48
Output = randresults/outs/ww48.out
Error = randresults/errs/ww48.err
Log = randresults/logs/ww48.log
queue

arguments = ww49
Output = randresults/outs/ww49.out
Error = randresults/errs/ww49.err
Log = randresults/logs/ww49.log
queue

arguments = ww50
Output = randresults/outs/ww50.out
Error = randresults/errs/ww50.err
Log = randresults/logs/ww50.log
queue

arguments = wz1
Output = randresults/outs/wz1.out
Error = randresults/errs/wz1.err
Log = randresults/logs/wz1.log
queue

arguments = wz2
Output = randresults/outs/wz2.out
Error = randresults/errs/wz2.err
Log = randresults/logs/wz2.log
queue

arguments = wz3
Output = randresults/outs/wz3.out
Error = randresults/errs/wz3.err
Log = randresults/logs/wz3.log
queue

arguments = wz4
Output = randresults/outs/wz4.out
Error = randresults/errs/wz4.err
Log = randresults/logs/wz4.log
queue

arguments = wz5
Output = randresults/outs/wz5.out
Error = randresults/errs/wz5.err
Log = randresults/logs/wz5.log
queue

arguments = wz6
Output = randresults/outs/wz6.out
Error = randresults/errs/wz6.err
Log = randresults/logs/wz6.log
queue

arguments = wz7
Output = randresults/outs/wz7.out
Error = randresults/errs/wz7.err
Log = randresults/logs/wz7.log
queue

arguments = wz8
Output = randresults/outs/wz8.out
Error = randresults/errs/wz8.err
Log = randresults/logs/wz8.log
queue

arguments = wz9
Output = randresults/outs/wz9.out
Error = randresults/errs/wz9.err
Log = randresults/logs/wz9.log
queue

arguments = wz10
Output = randresults/outs/wz10.out
Error = randresults/errs/wz10.err
Log = randresults/logs/wz10.log
queue

arguments = wz11
Output = randresults/outs/wz11.out
Error = randresults/errs/wz11.err
Log = randresults/logs/wz11.log
queue

arguments = wz12
Output = randresults/outs/wz12.out
Error = randresults/errs/wz12.err
Log = randresults/logs/wz12.log
queue

arguments = wz13
Output = randresults/outs/wz13.out
Error = randresults/errs/wz13.err
Log = randresults/logs/wz13.log
queue

arguments = wz14
Output = randresults/outs/wz14.out
Error = randresults/errs/wz14.err
Log = randresults/logs/wz14.log
queue

arguments = wz15
Output = randresults/outs/wz15.out
Error = randresults/errs/wz15.err
Log = randresults/logs/wz15.log
queue

arguments = wz16
Output = randresults/outs/wz16.out
Error = randresults/errs/wz16.err
Log = randresults/logs/wz16.log
queue

arguments = wz17
Output = randresults/outs/wz17.out
Error = randresults/errs/wz17.err
Log = randresults/logs/wz17.log
queue

arguments = wz18
Output = randresults/outs/wz18.out
Error = randresults/errs/wz18.err
Log = randresults/logs/wz18.log
queue

arguments = wz19
Output = randresults/outs/wz19.out
Error = randresults/errs/wz19.err
Log = randresults/logs/wz19.log
queue

arguments = wz20
Output = randresults/outs/wz20.out
Error = randresults/errs/wz20.err
Log = randresults/logs/wz20.log
queue

arguments = wz21
Output = randresults/outs/wz21.out
Error = randresults/errs/wz21.err
Log = randresults/logs/wz21.log
queue

arguments = wz22
Output = randresults/outs/wz22.out
Error = randresults/errs/wz22.err
Log = randresults/logs/wz22.log
queue

arguments = wz23
Output = randresults/outs/wz23.out
Error = randresults/errs/wz23.err
Log = randresults/logs/wz23.log
queue

arguments = wz24
Output = randresults/outs/wz24.out
Error = randresults/errs/wz24.err
Log = randresults/logs/wz24.log
queue

arguments = wz25
Output = randresults/outs/wz25.out
Error = randresults/errs/wz25.err
Log = randresults/logs/wz25.log
queue

arguments = wz26
Output = randresults/outs/wz26.out
Error = randresults/errs/wz26.err
Log = randresults/logs/wz26.log
queue

arguments = wz27
Output = randresults/outs/wz27.out
Error = randresults/errs/wz27.err
Log = randresults/logs/wz27.log
queue

arguments = wz28
Output = randresults/outs/wz28.out
Error = randresults/errs/wz28.err
Log = randresults/logs/wz28.log
queue

arguments = wz29
Output = randresults/outs/wz29.out
Error = randresults/errs/wz29.err
Log = randresults/logs/wz29.log
queue

arguments = wz30
Output = randresults/outs/wz30.out
Error = randresults/errs/wz30.err
Log = randresults/logs/wz30.log
queue

arguments = wz31
Output = randresults/outs/wz31.out
Error = randresults/errs/wz31.err
Log = randresults/logs/wz31.log
queue

arguments = wz32
Output = randresults/outs/wz32.out
Error = randresults/errs/wz32.err
Log = randresults/logs/wz32.log
queue

arguments = wz33
Output = randresults/outs/wz33.out
Error = randresults/errs/wz33.err
Log = randresults/logs/wz33.log
queue

arguments = wz34
Output = randresults/outs/wz34.out
Error = randresults/errs/wz34.err
Log = randresults/logs/wz34.log
queue

arguments = wz35
Output = randresults/outs/wz35.out
Error = randresults/errs/wz35.err
Log = randresults/logs/wz35.log
queue

arguments = wz36
Output = randresults/outs/wz36.out
Error = randresults/errs/wz36.err
Log = randresults/logs/wz36.log
queue

arguments = wz37
Output = randresults/outs/wz37.out
Error = randresults/errs/wz37.err
Log = randresults/logs/wz37.log
queue

arguments = wz38
Output = randresults/outs/wz38.out
Error = randresults/errs/wz38.err
Log = randresults/logs/wz38.log
queue

arguments = wz39
Output = randresults/outs/wz39.out
Error = randresults/errs/wz39.err
Log = randresults/logs/wz39.log
queue

arguments = wz40
Output = randresults/outs/wz40.out
Error = randresults/errs/wz40.err
Log = randresults/logs/wz40.log
queue

arguments = wz41
Output = randresults/outs/wz41.out
Error = randresults/errs/wz41.err
Log = randresults/logs/wz41.log
queue

arguments = wz42
Output = randresults/outs/wz42.out
Error = randresults/errs/wz42.err
Log = randresults/logs/wz42.log
queue

arguments = wz43
Output = randresults/outs/wz43.out
Error = randresults/errs/wz43.err
Log = randresults/logs/wz43.log
queue

arguments = wz44
Output = randresults/outs/wz44.out
Error = randresults/errs/wz44.err
Log = randresults/logs/wz44.log
queue

arguments = wz45
Output = randresults/outs/wz45.out
Error = randresults/errs/wz45.err
Log = randresults/logs/wz45.log
queue

arguments = wz46
Output = randresults/outs/wz46.out
Error = randresults/errs/wz46.err
Log = randresults/logs/wz46.log
queue

arguments = wz47
Output = randresults/outs/wz47.out
Error = randresults/errs/wz47.err
Log = randresults/logs/wz47.log
queue

arguments = wz48
Output = randresults/outs/wz48.out
Error = randresults/errs/wz48.err
Log = randresults/logs/wz48.log
queue

arguments = wz49
Output = randresults/outs/wz49.out
Error = randresults/errs/wz49.err
Log = randresults/logs/wz49.log
queue

arguments = wz50
Output = randresults/outs/wz50.out
Error = randresults/errs/wz50.err
Log = randresults/logs/wz50.log
queue

